### ISSUE TITLE
Unable to convert image to Mat

### ISSUE THREAD

**Issue by chaoticgood1** [jerry73204/rust-cv-convert#11]
I am doing the code below but it says:
`error[E0277]: the trait bound `opencv::prelude::Mat: TryFromCv<DynamicImage>` is not satisfied`

```
use cv_convert::{FromCv, IntoCv, TryFromCv, TryIntoCv};
let img = cv_convert::image::load_from_memory(src_img.buffer()).unwrap();
let mat: opencv::core::Mat = img.try_into_cv()?;
```
In my Cargo.toml
`cv-convert = { version = "0.21.2", features = ["image_0-24"] }`

Am I doing it wrong? Thanks.

**Comment by ChemicalXandco** [comment]
I have it working with:

```
cv-convert = { version = "0.21.2", features = ["image_0-24", "opencv_0-70"] }
image = "0.24"
opencv = version = "0.70.0"
```

**Comment by jerry73204** [comment]
@Nickan I rewrote the [README](https://github.com/jerry73204/rust-cv-convert/blob/master/cv-convert/README.md) for clarification. Now the up-to-date version enables the most recent dependencies by default. If you want to pick the versions on your own, change the features as it was.

```toml
[dependencies.cv-convert]
version = 'x.y.z'  # Please look up the recent version on crates.io
default-features = false  # Add this line to disable default dependencies.
features = [
    'image_0-24',
    'opencv_0-70',
]
```
