### ISSUE TITLE
Feature request: Add conversion from OpenCV to ndarray

### ISSUE THREAD

**Issue by Machine-Jonte** [jerry73204/rust-cv-convert#7]
I think converting OpenCV to ndarray would be a good feature. As Pyo3 has good support for converting numpy arrays to ndarrays, seems like a good feature to be able to convert OpenCV mat directly to ndarray as that enables python/rust OpenCV usage.

A possible conversion could be
```rust
trait AsArray {
    fn try_as_array(&self) -> Result<ArrayView3<u8>>;
}impl AsArray for cv::core::Mat {
    fn try_as_array(&self) -> Result<ArrayView3<u8>> {
        if !self.is_continuous() {
            return Err(anyhow!("Mat is not continuous"));
        }
        let bytes = self.data_bytes()?;
        let size = self.size()?;
        let a = ArrayView3::from_shape((size.height as usize, size.width as usize, 3), bytes)?;
        Ok(a)
    }
}
```

Though, this only works for continuous arrays.

**Comment by jerry73204** [comment]
It is implemented in [opencv-to-ndarray](https://github.com/jerry73204/rust-cv-convert/tree/opencv-to-ndarray) branch. You can see the usage in [test code](https://github.com/jerry73204/rust-cv-convert/blob/6cf7c2e9e42329a7cac681058d9062ca4b656479/src/with_opencv_ndarray.rs#L34-L38). Can you check if it works for you? 

To run the test,

```sh
cargo test --features ndarray_0-15,opencv_0-63 mat_ref_to_array_view_conversion
```

To include the new future in your crate, add this to `Cargo.toml`.

```toml
[dependencies]
cv-convert = { git = "https://github.com/jerry73204/rust-cv-convert.git", branch = "opencv-to-ndarray", features = ["ndarray_0-15", "opencv_0-63"] }
```
